package ar.com.exisoft.facundo.vista.paginas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InboxProveedorPage extends VerticalLayout {
	protected TextField nombreCliente;
	protected TextField telCliente;
	protected TextField direccionCliente;
	protected TextField faxCliente;
	protected TextField cuitCliente;
	protected TextField condicionPago;

	public InboxProveedorPage() {
		Design.read(this);
	}
}
